[content]
id = "01M25QYPMYRKESAMKM9VR3GTNR"
name = "R Markdown Params"
summary = "Render supplied report parameters."
entrypoint = "index.Rmd"
access_type = "internal"
content_type = "rmd"

[language]
name = "r"
packages = "renv.lock"

[packages]
r = { CRAN = "https://cran.rpkgs.com/" }

[static]
index = "index.html"
