[content]
name = "rmd-test"
entrypoint = "index.Rmd"
access_type = "internal"
content_type = "rmd"

[language]
name = "r"
packages = "renv.lock"

[packages]
r = { CRAN = "https://cran.rpkgs.com/" }

[static]
index = "index.html"
