[content]
id = "01KWMS7BJT7C6JFQCMN3GNMDSJ"
name = "user-jwt"
entrypoint = "plumber.R"
access_type = "external"
content_type = "plumber"

[language]
name = "r"
packages = "renv.lock"

[packages]
r = { CRAN = "https://cran.rpkgs.com/" }

[serve]
min_instances = 0
max_instances = 5
spawn_threshold = 80
max_connections = 10
