[content]
id = "01KFKWYNRM71R13ZFMH5V5NAXW"
name = "Plumber API"
entrypoint = "plumber.R"
access_type = "private"
content_type = "plumber"

[language]
name = "r"
packages = "renv.lock"

[serve]
min_instances = 0
max_instances = 5
spawn_threshold = 80
max_connections = 10
