[content]
id = "01KFKWYE2GJENS4AGZ8R8KT3JC"
name = "Hello, Ambiorix!"
entrypoint = "index.R"
access_type = "external"
content_type = "ambiorix"

[language]
name = "r"
packages = "renv.lock"

[serve]
min_instances = 0
max_instances = 5
spawn_threshold = 80
max_connections = 10
