[content]
name = "Dash Julia"
summary = "Adjust a power curve with a slider."
entrypoint = "app.jl"
access_type = "external"
content_type = "julia-service"

[language]
name = "julia"
packages = "Manifest.toml"
