[content]
name = "R Sleep"
summary = "Log timestamps for five minutes."
entrypoint = "main.R"
access_type = "private"
content_type = "r"

[language]
name = "r"
packages = "renv.lock"

[packages]
r = { CRAN = "https://cran.rpkgs.com/" }
