[content]
id = "01M25QYF9BWDBSYRHQN6G7ZA08"
name = "Python Sleep"
summary = "Log progress through nine timed iterations."
entrypoint = "main.py"
access_type = "private"
content_type = "python"

[language]
name = "python"
packages = "uv.lock"
