[content]
id = "01M25QYKGBM3187CNZ6C1SS6J2"
name = "Geocoding"
summary = "Find places by searching or clicking a map."
entrypoint = "app.R"
access_type = "private"
content_type = "shiny"

[language]
name = "r"
packages = "renv.lock"

[packages]
r = { CRAN = "https://cran.rpkgs.com/" }

[serve]
min_instances = 0
max_instances = 5
spawn_threshold = 80
max_connections = 10
