[content]
id = "01KFKWYFFNF1S0TSD06HSC69DZ"
name = "my bookdown "
entrypoint = "index.Rmd"
access_type = "private"
content_type = "rmd"

[language]
name = "r"
packages = "renv.lock"

[schedule]
cron = "@daily"
parameterized = false

[static]
index = "index.html"
output_dir = "_book"
