[content]
name = "R Functions"
entrypoint = "hello-world.R"
access_type = "external"
slug = "srvrless"
content_type = "serverless-r"
tags = ["serverless", "api", "server-fn"]
summary = "Expose R functions as HTTP endpoints."

[language]
name = "r"
packages = "renv.lock"

[packages]
r = { CRAN = "https://cran.rpkgs.com/" }
