[content]
name = "list headers"
entrypoint = "plumber.R"
access_type = "private"
content_type = "plumber"

[language]
name = "r"
packages = "renv.lock"

[serve]
min_instances = 0
max_instances = 5
spawn_threshold = 80
max_connections = 10
