[content]
name = "plumber2-penguins"
entrypoint = "_server.yml"
access_type = "external"
content_type = "r-server"

[language]
name = "r"
packages = "renv.lock"

[serve]
min_instances = 0
max_instances = 5
spawn_threshold = 80
max_connections = 10
