[content]
id = "01M25X3DDBXYF09FCJEMDYHBQ1"
name = "Plumber2 Pages"
summary = "Serve penguin pages styled with Tailwind CSS."
entrypoint = "app.R"
access_type = "external"
content_type = "r-server"

[language]
name = "r"
packages = "renv.lock"

[serve]
min_instances = 0
max_instances = 5
spawn_threshold = 80
max_connections = 10
