[content]
id = "01KFKWZ5149S3FGP0DCEF96SA4"
name = "reverse geocode"
entrypoint = "app.R"
access_type = "internal"
content_type = "shiny"

[language]
name = "r"
packages = "renv.lock"

[serve]
min_instances = 0
max_instances = 5
spawn_threshold = 80
max_connections = 10
