[content]
id = "01M25QYK06Z7A45XNAW0RP5ZCC"
name = "Ambiorix Counter"
summary = "Serve a page with a click counter."
entrypoint = "index.R"
access_type = "external"
content_type = "ambiorix"

[language]
name = "r"
packages = "renv.lock"

[packages]
r = { CRAN = "https://cran.rpkgs.com/" }

[serve]
min_instances = 0
max_instances = 5
spawn_threshold = 80
max_connections = 10
