[content]
id = "01M25QYQXV7RBF9DK0RR5CZ4JJ"
name = "Ambiorix CRUD"
summary = "Manage an in-memory member list."
entrypoint = "app.R"
access_type = "external"
content_type = "ambiorix"

[language]
name = "r"
packages = "renv.lock"

[packages]
r = { CRAN = "https://cran.rpkgs.com/" }

[serve]
min_instances = 0
max_instances = 5
spawn_threshold = 80
max_connections = 10
