[content]
name = "shiny-py-test"
entrypoint = "app.py"
access_type = "internal"
content_type = "shiny-py"

[language]
name = "python"
packages = "uv.lock"

[serve]
min_instances = 0
max_instances = 5
spawn_threshold = 80
max_connections = 10
