[content]
id = "01KTC5BHSKDS12PSMVVXK72N3R"
name = "security-audit"
entrypoint = "app.R"
access_type = "private"
content_type = "shiny"

[language]
name = "r"
packages = "renv.lock"

[packages]
r = { CRAN = "https://cran.rpkgs.com/" }

[serve]
min_instances = 0
max_instances = 5
spawn_threshold = 80
max_connections = 10
