[content]
name = "Hello, Streamlit!"
entrypoint = "app.py"
access_type = "external"
content_type = "streamlit"

[language]
name = "python"
packages = "uv.lock"

[serve]
min_instances = 0
max_instances = 5
spawn_threshold = 80
max_connections = 10
