[content]
id = "01M25QYRN3ARYBK925DG405Q8M"
name = "Entrypoints"
summary = "Switch entrypoints and stream session logs."
entrypoint = "a.R"
access_type = "internal"
content_type = "shiny"

[language]
name = "r"
packages = "renv.lock"

[packages]
r = { CRAN = "https://cran.rpkgs.com/" }

[serve]
min_instances = 0
max_instances = 5
spawn_threshold = 80
max_connections = 10
