[content]
id = "01M25QYHRBFVC6RWHWMQCW8YK7"
name = "Dash Python"
summary = "Display a Dash greeting."
entrypoint = "app.py"
access_type = "external"
content_type = "dash"

[language]
name = "python"
packages = "uv.lock"

[serve]
min_instances = 0
max_instances = 5
spawn_threshold = 80
max_connections = 10
