[content]
id = "01M25QYTGXPRA47AKZGY7B9ADF"
name = "Julia Penguins"
summary = "Inspect and plot penguin measurements."
entrypoint = "main.jl"
access_type = "private"
content_type = "julia"

[language]
name = "julia"
packages = "Manifest.toml"
