[content]
name = '"Plumber API"'
entrypoint = "plumber.R"
access_type = "external"
content_type = "plumber"
id = "01K6P3M6Q4FCXHMTKEKQX8P11V"

[language]
name = "r"
packages = "renv.lock"

[serve]
min_instances = 0
max_instances = 5
spawn_threshold = 80
max_connections = 10
