[content]
id = "01KJDSS18YYB4SEAVDFDP9M2X9"
name = "Hello, FastAPI!"
entrypoint = "app.py"
access_type = "external"
content_type = "fast-api"

[language]
name = "python"
packages = "uv.lock"

[serve]
min_instances = 0
max_instances = 5
spawn_threshold = 80
max_connections = 10
